### ISSUE TITLE
Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by gangrelg** [MarcGodard/merge-images-v2#1]
Hi, this is probably not an issue, but how the canvas work for security reasons. I'm currently getting images from an API with React. Im trying to print the b64 as a result from the callback, but I get that error. Is there a way I can actually handle the b64 without this problem?

The server headers are allowing almost everything.

Thank to anyone committed to help.

PD: Yeah, with local images, the package works perfectly (Currently need it to work with API's)

**Comment by gangrelg** [comment]
@MarcGodard

**Comment by MarcGodard** [comment]
This is a problem with browser security. I have encountered it before, can't remember how I solved this. Let me look into this.

**Comment by MarcGodard** [comment]
Because this isn't an issue with the library, and is a browser security issue, I will close this issue.

I haven't seen specific problem again, but I remember encountering it when loading images from another domain.

**Comment by judiel-camonapp** [comment]
Hi, i'm facing with this problem, i've see in the previous version the `options` object revice an `crossOrigin` attr and now is not avaliable.

**Comment by sarah-i-rubenstein** [comment]
@gangrelg Did you ever solve this issue?

**Comment by MarcGodard** [comment]
@judiel-camonapp Sorry just saw this, will look into that this weekend.

@sarah-i-rubenstein What i the error you are getting specifically? I just want to keep issues clear so I can make sure I am working on the right problems.

**Comment by sarah-i-rubenstein** [comment]
I am getting this error: 
DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

...this only happens when I attempt to use an image url that I am pulling from an API. I tried solve this problem by setting crossOrigin to anonymous on all of the images, but that doesn't work.

**Comment by gangrelg** [comment]
Hey! I remember solving this issue I was having to the point I’ve forked the solution to adapt to my needs. I don’t remember exactly if it was that forked custom package or some server related configs.

**Comment by MarcGodard** [comment]
@gangrelg Feel free to do a pull request if you have found a code solution.
