### ISSUE TITLE
mergeImages is not defined

### ISSUE THREAD

**Issue by p2gdeveloper** [MarcGodard/merge-images-v2#2]
No matter where I try using this I get a "mergeImages is not defined" every time, even with a very basic merge like the one I try in this [jsfiddle](https://jsfiddle.net/willcom/rcL97e2b/4/). If I try the original merge images by Luke Childs that works, but I need the ability to resize source images.

I should point out that I'm using a CDN - https://cdn.jsdelivr.net/npm/merge-images-v2@2.0.1/dist/index.umd.min.js so I guess it is possible that the problem lies there but it does lead to the correct original npm file. Also, I get the same error if I try running on runkit.

**Comment by MarcGodard** [comment]
I am not sure if this is a jsfiddle issue or the CDN, but sounds like the CDN. I didn't make any changed to Luke's version that would cause this.

If you figure it out and its an issue with the lib, feel free to submit a PR.

**Comment by p2gdeveloper** [comment]
Thanks for coming back to me. I'm also inclined to think it is the CDN, except that using runKit from npmjs.com gives me the same error. I seem to get further if I use mergeImagesV2([ ]) instead of mergeImages([ ]) but then I hot other issues down the line with tainted image errors which I don't get if I use Luke's original version. Strange. 

I'm not a JS developer so it's probably something that I'm doing wrong, especially if others are able to use it successfully. 

If you know of any alternative CDN (I kind of do have to use one) then I'd be really grateful if you could let me know. I have searched without much success. Thanks again.

**Comment by MarcGodard** [comment]
Sorry you are getting other issues. These might have to do with other changes, not sure. I did simplify some of his code for my own uses. I don't know what could cause it and I can look into this at some point (especially if others have issues). I don't know of any CDN that has my version of this lib, so thanks for showing me that.
